name: Poreformer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pysam
  - python>=3.8
  - tensorflow==2.0.0
  - h5py
  - ont-fast5-api
  - pip
  - samtools==1.12
  - minimap2
  - pip:
    - pod5
    